Use more flexible git_version.h that can handle separate build dir.

diff --git a/tools/Makefile.am b/tools/Makefile.am
--- a/tools/Makefile.am
+++ b/tools/Makefile.am
@@ -1,3 +1,27 @@
+GIT_VERSION_CMD = $(SHELL) $(top_srcdir)/scripts/git_version.sh
+git_version.stamp:
+	@if test -f "$(srcdir)/git_version.h"; then \
+		if test -f "git_version.h"; then :; \
+		else \
+			cp "$(srcdir)/git_version.h" "git_version.h"; \
+		fi; \
+	fi
+	$(GIT_VERSION_CMD) -k -s $(top_srcdir) -o git_version.h
+	@if test -s "$(srcdir)/git_version.h"; then \
+		if cmp "$(srcdir)/git_version.h" "git_version.h"; then :; \
+		else \
+			echo "Error: $(srcdir)/git_version.h and git_version.h differ."; \
+			echo "       You probably want to remove the former."; \
+			exit 1; \
+		fi; \
+	fi
+
+dist-hook: git_version.stamp
+	if test -f "git_version.h"; then \
+		$(SED) -e 's|^#undef GIT_IS_DIST.*|#define GIT_IS_DIST 1|' \
+			"git_version.h" > "$(distdir)/git_version.h"; \
+	fi
+
 LDADD       = @top_builddir@/otc/libotcetera.la
 AM_CPPFLAGS = -I@top_srcdir@/otc $(BOOST_CPPFLAGS)
 AM_LDFLAGS = $(BOOST_PROGRAM_OPTIONS_LDFLAGS)
@@ -117,11 +141,13 @@ otc_tree_tool_CPPFLAGS = $(AM_CPPFLAGS)
 otc_unprune_solution_and_name_unnamed_nodes_SOURCES = unprune-solution-and-name-unnamed-nodes.cpp
 otc_unprune_solution_and_name_unnamed_nodes_CPPFLAGS = $(AM_CPPFLAGS)
 
-gitversion.h: $(abs_top_srcdir)/.git/HEAD $(abs_top_srcdir)/.git/index
-	echo "const char *gitversion = \"$(shell git rev-parse HEAD)\";" > $@
-
-otc_version_reporter_SOURCES = $(builddir)/gitversion.h version-reporter.cpp
+otc_version_reporter_SOURCES = version-reporter.cpp
 otc_version_reporter_CPPFLAGS = $(AM_CPPFLAGS)
+
+nodist_otc_version_reporter_SOURCES = git_version.h
+
+# always "rebuild" these
+BUILT_SOURCES = version-reporter.cpp git_version.stamp
 
 check:
 	python $(abs_top_srcdir)/tools/test_otc_tools.py $(abs_top_srcdir)/data $(abs_top_srcdir)/expected $(abs_builddir)
